### ISSUE TITLE
Upload test results to codecov

### ISSUE THREAD

**Issue by mattdot** [microsoft/terraform-provider-power-platform#643]
# User Story
As a maintainer, I would like to track the test pass/fail rates using codecov so that we can manage code quality better.

## Details

Ensure that the run_test.yml pipeline is outputting junit xml test results that can be uploaded to codecov.io.  Though `go test` does not natively support junit format, it can easily be converted using `go-junit-report`

How to install in pipeline
```
go install github.com/jstemmer/go-junit-report/v2@latest
```

Example usage (from https://github.com/jstemmer/go-junit-report )

```bash
go test -v 2>&1 ./... | go-junit-report -set-exit-code > report.xml
```

Example upload to codecov 

```yaml
      - name: Upload test results to Codecov
      	if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
```
