### ISSUE TITLE
Update GitHub workflows to use GITHUB_OUTPUT

### ISSUE THREAD

**Issue by mattdot** [microsoft/terraform-provider-power-platform#645]
We need to proactively change our github actions/workflows to stop using a deprecated feature 

> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

A workflow using save-state or set-output like the following

``` yaml
- name: Save state
run: echo "::save-state name={name}::{value}"

- name: Set output
run: echo "::set-output name={name}::{value}"
```

should be updated to write to the new GITHUB_STATE and GITHUB_OUTPUT environment files:

```yaml
- name: Save state
run: echo "{name}={value}" >> $GITHUB_STATE

- name: Set output
run: echo "{name}={value}" >> $GITHUB_OUTPUT
```
